options:
  service-plugins:
    type: string
    description: |
      Neutron's service plugins.
      This is default value from neutron-charm plus bgp plugin. We need to redefine it cause neutron-api charm doesn't allow to pass just additional plugins
    default: "router,firewall,vpnaas,metering,neutron_lbaas.services.loadbalancer.plugin.LoadBalancerPluginv2,neutron_dynamic_routing.services.bgp.bgp_plugin.BgpPlugin"