- job:
    name: juju-destroy-environment
    description: "Destroys existing default Juju environment"
    defaults: global
    properties:
      - build-discarder:
          num-to-keep: 3
    builders:
      - shell: |
          #!/bin/bash -e
          juju destroy-controller -y --destroy-all-models amazon
